### ISSUE TITLE
reqres, why?

### ISSUE THREAD

**Issue by canvaspixels** [marionettejs/backbone.wreqr#60]
I just came across this and I completely agree. Are there plans to remove reqres? Please could somebody give a counter argument or explain a scenario of when reqres would benefit me. If this is the wrong place to put this, please point me in the right direction, thanks!

**Comment by canvaspixels** [comment]
Thanks for that very in depth response. I'm a lot clearer on this now.

Re: I'm curious to hear why you think request-reply makes sense in the client-server situation.
I'm not sure, I guess because they are more disconnected?

**Comment by jmeas** [comment]
> I'm not sure, I guess because they are more disconnected?

Heh, yeah. They *are* disconnected – and often times you want them to be – which is why a messaging patterns seems to make sense. The point I was trying to make here, if you didn't catch it, is that if you want to have disconnected pieces *on the client* (again, think **big** apps), then you might appreciate evented architecture there, too.

**Comment by jmeas** [comment]
I already started on [a response](https://github.com/marionettejs/blog/pull/12) to another anti-reqres blog. I'm not that interested in spending time content on our blog til it's a little better :(
