### ISSUE TITLE
Version number inconsistency

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.wreqr#71]
Package.json is v1.3.4 but all contents of lib say 1.3.3. Led to some confusion when installing deps for Marionette. Not a huge deal since it's all going to be deprecated, but was confused as to how/why it happened.

**Comment by jmeas** [comment]
It happens when the publish steps are completed out of order. `package.json` needs to be updated *first*, then the library is built. The [grunt template task](https://github.com/marionettejs/backbone.wreqr/blob/master/Gruntfile.js#L33-L41) is what puts the version number into the built lib.

We should cut a 1.3.5 release with the correct version numbas.

**Comment by MeoMix** [comment]
It's fixed! Thanks!
